const translations = {
  en: {
    common: {
      brand: "OpenClaw Finder",
      navAbout: "About",
      navSubmit: "Submit",
      navContact: "Contact",
      navPrivacy: "Privacy",
    },
    project: {
      common: {
        quickFacts: "Quick facts",
        status: "Status",
        type: "Type",
        bestFor: "Best for",
        whatItIs: "What it is",
        whyItMatters: "Why it matters",
        notablePoints: "Notable points",
        sources: "Sources",
      },
      openclaw: {
        title: "OpenClaw | OpenClaw Finder",
        description: "Profile for OpenClaw, the main personal AI assistant runtime and official ecosystem entry point.",
        kicker: "Official runtime",
        name: "OpenClaw",
        summary: "The core OpenClaw project and personal AI assistant runtime, backed by an official site, public docs, and an open GitHub repository.",
        statusValue: "Confirmed official project",
        typeValue: "Main runtime",
        bestForValue: "Starting from the primary ecosystem entry point",
        body1: "OpenClaw is the flagship project in this ecosystem. Public materials position it as a personal AI assistant runtime with an onboarding flow, official documentation, and broad messaging platform integrations.",
        body2: "If someone wants to understand the OpenClaw ecosystem from the source, this is the first project to study. It defines the core product direction and anchors the surrounding docs, skills, and workflow tools.",
        point1: "Official site, docs, and GitHub repo are publicly available.",
        point2: "Docs reference a command-led onboarding flow.",
        point3: "Public repository materials describe integrations across many messaging platforms.",
        source1: "Official site",
        source2: "Official docs",
        source3: "GitHub repository",
      },
      picoclaw: {
        title: "PicoClaw | OpenClaw Finder",
        description: "Profile for PicoClaw, a lightweight Go-based OpenClaw-style assistant for low-resource environments.",
        kicker: "Low-resource runtime",
        name: "PicoClaw",
        summary: "A Go-based OpenClaw-style assistant built for extremely small hardware and low memory footprints.",
        statusValue: "Confirmed public repository",
        typeValue: "Lightweight runtime",
        bestForValue: "Edge devices and low-cost hardware",
        body1: "PicoClaw positions itself as an ultra-efficient assistant implementation with a strong emphasis on constrained environments. Public repository materials describe Go-based performance characteristics and very small hardware targets.",
        body2: "This project matters because it pushes the ecosystem toward cheaper, lower-power deployments. It is a useful counterpoint to heavier agent runtimes.",
        point1: "Repository README emphasizes low RAM and low-cost hardware operation.",
        point2: "Official README warns that many similar domains are third-party registrations.",
        point3: "Implemented in Go rather than following the exact stack of the main project.",
        source1: "GitHub repository",
      },
      nanoclaw: {
        title: "NanoClaw | OpenClaw Finder",
        description: "Profile for NanoClaw, a container-focused lightweight alternative in the OpenClaw ecosystem.",
        kicker: "Container-first runtime",
        name: "NanoClaw",
        summary: "A lightweight alternative that emphasizes containerized execution and safer isolation boundaries.",
        statusValue: "Confirmed public repository",
        typeValue: "Alternative runtime",
        bestForValue: "Security-conscious deployments",
        body1: "NanoClaw presents itself as a lightweight alternative to OpenClaw that runs in containers for security. Public materials also mention multiple messaging and email integrations.",
        body2: "It demonstrates a different philosophy inside the ecosystem: keep the assistant small, but use containers to create cleaner isolation and deployment boundaries.",
        point1: "Official website and repository are both publicly available.",
        point2: "Repository description explicitly calls out containers for security.",
        point3: "Good candidate for users who want a self-hosted but more controlled runtime surface.",
        source1: "Official site",
        source2: "GitHub repository",
      },
      zeroclaw: {
        title: "ZeroClaw | OpenClaw Finder",
        description: "Profile for ZeroClaw, a Rust-based runtime and infrastructure path in the OpenClaw ecosystem.",
        kicker: "Rust runtime",
        name: "ZeroClaw",
        summary: "A Rust-based runtime and infrastructure path with migration tooling for existing OpenClaw users.",
        statusValue: "Confirmed public repository",
        typeValue: "Alternative runtime and infra stack",
        bestForValue: "Infra-minded users and migrations",
        body1: "ZeroClaw takes a lower-level systems route through Rust and presents itself as autonomous assistant infrastructure rather than just another UI wrapper.",
        body2: "It matters because it offers a migration story and a different implementation philosophy for users who care about performance, systems control, and runtime footprint.",
        point1: "Repository materials describe migration commands from OpenClaw.",
        point2: "Rust positioning makes it distinct from lighter Go implementations and the primary project stack.",
        point3: "Useful to watch if your audience cares about infrastructure more than consumer polish.",
        source1: "GitHub repository",
      },
      clawhub: {
        title: "ClawHub | OpenClaw Finder",
        description: "Profile for ClawHub, the official skill marketplace and registry around OpenClaw.",
        kicker: "Official ecosystem tool",
        name: "ClawHub",
        summary: "The official marketplace and registry for discovering, installing, and publishing OpenClaw skills.",
        statusValue: "Confirmed official project",
        typeValue: "Skill registry",
        bestForValue: "Discovering and distributing skills",
        body1: "ClawHub is part of the official tooling layer around OpenClaw. It serves as the place where skills can be found, installed, and shared.",
        body2: "A healthy ecosystem needs extension points, not only a runtime. ClawHub is one of the clearest signals that OpenClaw is trying to support a broader tool and skill marketplace.",
        point1: "Documented in the official OpenClaw docs.",
        point2: "Backed by a public GitHub repository.",
        point3: "Good fit for a separate ecosystem category inside your directory.",
        source1: "Official docs",
        source2: "GitHub repository",
      },
      openprose: {
        title: "OpenProse | OpenClaw Finder",
        description: "Profile for OpenProse, the official workflow and orchestration format around OpenClaw.",
        kicker: "Official workflow format",
        name: "OpenProse",
        summary: "The official workflow and orchestration format for structured multi-agent OpenClaw setups.",
        statusValue: "Confirmed official ecosystem",
        typeValue: "Workflow language and orchestration layer",
        bestForValue: "Structured multi-agent workflows",
        body1: "OpenProse is the official workflow layer documented around OpenClaw. It is positioned as the way to express more structured orchestration instead of running everything as one flat assistant flow.",
        body2: "This matters because mature ecosystems need a workflow abstraction, not just tools and agents. OpenProse signals that OpenClaw is thinking about programmable composition.",
        point1: "Officially documented under the OpenClaw docs site.",
        point2: "Useful as a separate ecosystem entry, not as a runtime replacement.",
        point3: "Good candidate for future content around comparisons and workflow examples.",
        source1: "Official docs",
      },
      qclaw: {
        title: "QClaw | OpenClaw Finder",
        description: "Profile for QClaw, a watched but not yet strongly confirmed OpenClaw-related project.",
        kicker: "Watching",
        name: "QClaw",
        summary: "A project name that appears in media and community discussion, but is not yet backed here by a strong public primary source.",
        statusValue: "Watching / unverified",
        typeValue: "Possible ecosystem variant",
        bestForValue: "Tracking until an official source appears",
        body1: "QClaw has been mentioned in secondary coverage and community discussion as a possible Tencent-flavored OpenClaw variant. At the time of writing, this directory has not located a sufficiently strong official public source to classify it as confirmed.",
        body2: "It matters because people searching this ecosystem may already be seeing the name. Recording it with a clear confidence label is more useful than pretending it does not exist or overstating certainty.",
        point1: "Not currently treated here as a confirmed public release.",
        point2: "Should be upgraded only if a clear official repository, docs site, or launch page appears.",
        point3: "Good example of why the directory separates confirmed entries from watched names.",
        source1: "No primary-source link listed yet. Keep this profile as a watching page until one is confirmed.",
      },
    },
    home: {
      title: "OpenClaw Finder | Discover OpenClaw Projects",
      description:
        "OpenClaw Finder is a curated directory for discovering OpenClaw projects, tools, and experiments such as qclaw and picoclaw.",
      eyebrow: "Curated directory",
      heroTitle: "Find the best OpenClaw projects in one place.",
      heroLead:
        "A fast, searchable index of OpenClaw runtimes, ecosystem tools, and experiments. Compare what exists, follow new launches, and submit projects to be featured.",
      browse: "Browse directory",
      submit: "Submit a project",
      profileLink: "Profile",
      statusLabel: "Launch status",
      statusValue: "Public beta",
      statusItem1: "Curated manually",
      statusItem2: "Built for global access",
      statusItem3: "Open to sponsorships later",
      signal1Value: "Primary sources",
      signal1Label: "Repos, docs, and official launch pages only",
      signal2Value: "Global-first",
      signal2Label: "Built for bilingual discovery and public indexing",
      signal3Value: "Human-curated",
      signal3Label: "Verified projects separated from rumor and noise",
      feature1Title: "Discover",
      feature1Body: "Browse active OpenClaw projects without digging through scattered links.",
      feature2Title: "Compare",
      feature2Body: "Use tags and summaries to quickly judge what is worth trying.",
      feature3Title: "Track",
      feature3Body: "Follow updates as new OpenClaw tools and variants launch.",
      directoryEyebrow: "Featured projects",
      directoryTitle: "Starting directory",
      directoryLead:
        "A first-pass directory of verified OpenClaw runtimes and official ecosystem projects, based on public primary sources.",
      card1Tag: "Watching",
      card1Body:
        "Reported as a Tencent-flavored OpenClaw variant in media and community posts, but not yet confirmed by a strong public primary source.",
      card1Meta1: "Status: Unverified public availability",
      card1Meta2: "Category: Watching",
      card2Tag: "Official",
      card2Body:
        "The main project and personal AI assistant runtime, with an official site, docs, and open GitHub repository.",
      card2Meta1: "Status: Confirmed official project",
      card2Meta2: "Best for: Starting with the main ecosystem",
      card3Title: "PicoClaw",
      card3Tag: "Lightweight",
      card3Body:
        "A Go-based low-resource OpenClaw-style assistant designed for extremely small hardware and memory budgets.",
      card3Meta1: "Status: Confirmed public repo",
      card3Meta2: "Best for: Edge devices and low-cost hardware",
      card4Tag: "Container-first",
      card4Body:
        "A lightweight alternative focused on containerized execution and safer isolation.",
      card4Meta1: "Status: Confirmed public repo",
      card4Meta2: "Best for: Secure, containerized deployments",
      card5Tag: "Rust",
      card5Body:
        "A Rust-based runtime and infrastructure approach with migration tooling for existing OpenClaw users.",
      card5Meta1: "Status: Confirmed public repo",
      card5Meta2: "Best for: Infra-minded users and migrations",
      card6Tag: "Ecosystem",
      card6Body:
        "The official skill marketplace and registry for installing and publishing OpenClaw skills.",
      card6Meta1: "Status: Confirmed official project",
      card6Meta2: "Best for: Discovering and distributing skills",
      card7Tag: "Workflow",
      card7Body:
        "The official workflow and orchestration format for multi-agent OpenClaw setups.",
      card7Meta1: "Status: Confirmed official ecosystem",
      card7Meta2: "Best for: Structured multi-agent workflows",
      ctaEyebrow: "Grow the directory",
      ctaTitle: "Want your OpenClaw project listed?",
      ctaBody:
        "Use the submission page to send your project name, URL, short description, and launch notes.",
      ctaButton: "Submit now",
      footerText: "The public directory for discovering OpenClaw projects.",
    },
    about: {
      title: "About | OpenClaw Finder",
      description: "Learn what OpenClaw Finder is, who it is for, and how projects are selected.",
      eyebrow: "About",
      bodyTitle: "Why this site exists",
      body1:
        "OpenClaw Finder is a curated navigation site for people trying to understand the growing OpenClaw ecosystem. The goal is simple: make it easier to discover projects, compare them quickly, and follow new launches without digging across scattered links.",
      section1Title: "What gets listed",
      section1Body:
        "Projects should be directly relevant to the OpenClaw ecosystem and should point to a working homepage, repository, or product page. Entries may be edited for clarity and consistency.",
      section2Title: "How listings are reviewed",
      section2Body:
        "Submissions are reviewed manually before they appear on the site. That helps keep the directory useful and reduces low-quality entries.",
    },
    submit: {
      title: "Submit a Project | OpenClaw Finder",
      description: "Submit an OpenClaw project for review and listing on OpenClaw Finder.",
      eyebrow: "Submit",
      bodyTitle: "Submit your OpenClaw project",
      body1:
        "For now, submissions are handled manually. Send the following details by email and the project can be reviewed for inclusion.",
      emailLabel: "Email:",
      includeLabel: "Include:",
      includeBody: "project name, URL, one-line summary, and what makes it different.",
      body2:
        "After you set up email forwarding or an inbox provider, replace this page with a form or link it to a form tool such as Tally, Typeform, or Formspree.",
    },
    contact: {
      title: "Contact | OpenClaw Finder",
      description: "Contact OpenClaw Finder for project submissions, feedback, and future sponsorships.",
      eyebrow: "Contact",
      bodyTitle: "Get in touch",
      body1:
        "Reach out for directory feedback, corrections, partnerships, or future advertising and sponsorship enquiries.",
      emailLabel: "Email:",
      responseLabel: "Response time:",
      responseBody: "usually within a few business days.",
    },
    privacy: {
      title: "Privacy Policy | OpenClaw Finder",
      description: "Privacy policy for OpenClaw Finder.",
      eyebrow: "Privacy",
      bodyTitle: "Privacy policy",
      body1:
        "OpenClaw Finder may collect basic analytics information such as page views, referring pages, and browser information to understand site usage.",
      body2:
        "If you email a submission or contact request, your message and contact details are used only to review your project or reply to your enquiry.",
      body3:
        "This site may use third-party services such as analytics or advertising providers in the future. This page should be updated before those services are enabled.",
    },
  },
  zh: {
    common: {
      brand: "OpenClaw Finder",
      navAbout: "关于",
      navSubmit: "提交项目",
      navContact: "联系",
      navPrivacy: "隐私",
    },
    project: {
      common: {
        quickFacts: "快速信息",
        status: "状态",
        type: "类型",
        bestFor: "适合",
        whatItIs: "这是什么",
        whyItMatters: "为什么重要",
        notablePoints: "关键信息",
        sources: "来源",
      },
      openclaw: {
        title: "OpenClaw | OpenClaw Finder",
        description: "OpenClaw 项目详情页，主项目本体，也是官方生态入口。",
        kicker: "官方运行时",
        name: "OpenClaw",
        summary: "OpenClaw 生态的核心项目，也是个人 AI Assistant 运行时，拥有官网、公开文档和 GitHub 仓库。",
        statusValue: "已确认官方项目",
        typeValue: "主运行时",
        bestForValue: "从官方主入口理解整个生态",
        body1: "OpenClaw 是这个生态里的旗舰项目。公开资料将它定位为个人 AI Assistant 运行时，具备 onboarding 流程、官方文档以及广泛的消息平台集成。",
        body2: "如果你想从源头理解 OpenClaw 生态，这是最应该先研究的项目。它定义了核心产品方向，并连接周边文档、skills 和 workflow 工具。",
        point1: "官网、文档和 GitHub 仓库均公开可访问。",
        point2: "文档里明确给出了基于命令的 onboarding 流程。",
        point3: "仓库公开资料描述了多种消息平台集成能力。",
        source1: "官网",
        source2: "官方文档",
        source3: "GitHub 仓库",
      },
      picoclaw: {
        title: "PicoClaw | OpenClaw Finder",
        description: "PicoClaw 项目详情页，一个面向低资源环境的 Go 实现。",
        kicker: "低资源运行时",
        name: "PicoClaw",
        summary: "一个基于 Go 的 OpenClaw 风格助手，面向极小硬件和低内存环境。",
        statusValue: "已确认公开仓库",
        typeValue: "轻量运行时",
        bestForValue: "边缘设备和低成本硬件",
        body1: "PicoClaw 把自己定位为超高效率的助手实现，重点针对受限环境。公开仓库资料强调了 Go 的实现方式和超小硬件目标。",
        body2: "它的重要性在于把生态向更便宜、更低功耗的部署方式推进，是对更重型 agent runtime 的一个有价值对照。",
        point1: "README 强调低 RAM 和低成本硬件运行。",
        point2: "官方 README 提醒很多相似域名是第三方注册。",
        point3: "采用 Go 实现，这一点和主项目栈不同。",
        source1: "GitHub 仓库",
      },
      nanoclaw: {
        title: "NanoClaw | OpenClaw Finder",
        description: "NanoClaw 项目详情页，一个容器优先的轻量替代方案。",
        kicker: "容器优先运行时",
        name: "NanoClaw",
        summary: "一个强调容器化执行和更安全隔离边界的轻量替代方案。",
        statusValue: "已确认公开仓库",
        typeValue: "替代运行时",
        bestForValue: "重视安全的部署场景",
        body1: "NanoClaw 将自己定位为 OpenClaw 的轻量替代方案，并明确强调通过容器实现更好的安全隔离。公开资料还提到多种消息和邮件集成。",
        body2: "它体现了生态中的另一条路线：保持系统小巧，同时用容器获得更清晰的隔离和部署边界。",
        point1: "官网和仓库都公开可用。",
        point2: "仓库描述明确提到用容器提升安全性。",
        point3: "适合想要自托管但更强调控制边界的用户。",
        source1: "官网",
        source2: "GitHub 仓库",
      },
      zeroclaw: {
        title: "ZeroClaw | OpenClaw Finder",
        description: "ZeroClaw 项目详情页，一个基于 Rust 的运行时和基础设施路线。",
        kicker: "Rust 运行时",
        name: "ZeroClaw",
        summary: "一个基于 Rust 的运行时和基础设施路线，并提供面向 OpenClaw 用户的迁移能力。",
        statusValue: "已确认公开仓库",
        typeValue: "替代运行时和基础设施栈",
        bestForValue: "偏基础设施和迁移需求的用户",
        body1: "ZeroClaw 选择了更底层的 Rust 路线，并把自己描述为自治助手基础设施，而不仅仅是另一个 UI 包装层。",
        body2: "它的重要性在于提供了迁移故事和不同的实现哲学，适合关心性能、系统控制和运行时体积的用户。",
        point1: "仓库资料描述了从 OpenClaw 迁移的命令。",
        point2: "Rust 路线让它和 Go 轻量实现、以及主项目都形成差异。",
        point3: "如果你的受众更看重基础设施而不是消费级体验，这是值得关注的项目。",
        source1: "GitHub 仓库",
      },
      clawhub: {
        title: "ClawHub | OpenClaw Finder",
        description: "ClawHub 项目详情页，OpenClaw 官方技能市场和注册表。",
        kicker: "官方生态工具",
        name: "ClawHub",
        summary: "OpenClaw 官方的 marketplace 和 registry，用于发现、安装和发布 skills。",
        statusValue: "已确认官方项目",
        typeValue: "技能注册表",
        bestForValue: "发现和分发技能",
        body1: "ClawHub 是 OpenClaw 官方工具层的一部分，承担了发现、安装和共享 skills 的角色。",
        body2: "一个成熟生态不能只有运行时，还需要扩展点。ClawHub 是 OpenClaw 正在建设更大工具和 skill 市场的明确信号。",
        point1: "在官方文档中有明确记录。",
        point2: "有公开 GitHub 仓库支撑。",
        point3: "非常适合作为目录中的独立生态分类。",
        source1: "官方文档",
        source2: "GitHub 仓库",
      },
      openprose: {
        title: "OpenProse | OpenClaw Finder",
        description: "OpenProse 项目详情页，OpenClaw 官方工作流和编排格式。",
        kicker: "官方工作流格式",
        name: "OpenProse",
        summary: "OpenClaw 官方的 workflow 和 orchestration 格式，适合结构化多 agent 场景。",
        statusValue: "已确认官方生态",
        typeValue: "工作流语言和编排层",
        bestForValue: "结构化多 agent 工作流",
        body1: "OpenProse 是围绕 OpenClaw 的官方工作流层。它被定位为表达更结构化 orchestration 的方式，而不是把所有逻辑都塞进一个平面助手流程。",
        body2: "它的重要性在于成熟生态需要 workflow 抽象，而不只是工具和 agent。OpenProse 说明 OpenClaw 已经在考虑可编程组合。",
        point1: "在 OpenClaw 官方文档中有明确页面。",
        point2: "它更适合作为生态条目，而不是运行时替代品。",
        point3: "后面很适合扩展成 comparison 和 workflow example 内容。",
        source1: "官方文档",
      },
      qclaw: {
        title: "QClaw | OpenClaw Finder",
        description: "QClaw 项目详情页，当前处于关注中，尚未拿到足够强的官方一手来源确认。",
        kicker: "关注中",
        name: "QClaw",
        summary: "一个在媒体和社区讨论中出现过的项目名，但目前还没有足够强的公开一手来源支撑。",
        statusValue: "关注中 / 未确认",
        typeValue: "可能的生态变体",
        bestForValue: "持续跟踪，等待官方来源出现",
        body1: "QClaw 在二手报道和社区讨论里被提到为可能的腾讯风格 OpenClaw 变体。到目前为止，这个目录还没有找到足够强的官方公开来源来把它归类为已确认项目。",
        body2: "它值得记录，因为用户在搜索生态时可能已经会看到这个名字。用明确置信度标签记录它，比假装不存在或过度下结论更有价值。",
        point1: "当前不视为已确认公开发布。",
        point2: "只有出现明确官方仓库、文档站或发布页后，才建议升级状态。",
        point3: "这也是为什么目录要把已确认项目和关注中项目分开展示。",
        source1: "目前没有列出一手来源链接，在确认前保持关注页状态。",
      },
    },
    home: {
      title: "OpenClaw Finder | 发现 OpenClaw 项目",
      description:
        "OpenClaw Finder 是一个精选导航站，用来发现 qclaw、picoclaw 等 OpenClaw 项目、工具和实验。",
      eyebrow: "精选导航",
      heroTitle: "在一个地方找到值得关注的 OpenClaw 项目。",
      heroLead:
        "这是一个快速、可浏览的 OpenClaw 运行时、生态工具和实验项目索引。你可以查看现有项目、跟踪新发布内容，并提交项目申请收录。",
      browse: "浏览目录",
      submit: "提交项目",
      profileLink: "详情",
      statusLabel: "上线状态",
      statusValue: "公开测试版",
      statusItem1: "人工精选整理",
      statusItem2: "面向全球访问",
      statusItem3: "后续可接赞助",
      signal1Value: "一手来源",
      signal1Label: "只收录仓库、文档和官方发布页",
      signal2Value: "全球优先",
      signal2Label: "按双语发现和公开索引方式构建",
      signal3Value: "人工整理",
      signal3Label: "把已核实项目和传闻信息分开展示",
      feature1Title: "发现项目",
      feature1Body: "不用在零散链接里来回查找，直接浏览活跃的 OpenClaw 项目。",
      feature2Title: "快速比较",
      feature2Body: "通过标签和摘要快速判断哪个项目值得尝试。",
      feature3Title: "持续跟踪",
      feature3Body: "关注新的 OpenClaw 工具和变体发布动态。",
      directoryEyebrow: "精选项目",
      directoryTitle: "起步目录",
      directoryLead: "基于公开一手来源整理的第一批目录，包含已确认的 OpenClaw 运行时和官方生态项目。",
      card1Tag: "关注中",
      card1Body: "目前在媒体和社区讨论里被提到为腾讯风格的 OpenClaw 变体，但我还没查到足够强的官方一手公开来源。",
      card1Meta1: "状态：公开可用性待确认",
      card1Meta2: "分类：关注中",
      card2Tag: "官方",
      card2Body: "主项目本体，也是个人 AI Assistant 运行时，有官网、文档和公开 GitHub 仓库。",
      card2Meta1: "状态：已确认官方项目",
      card2Meta2: "适合：从主生态开始了解",
      card3Title: "PicoClaw",
      card3Tag: "轻量",
      card3Body: "一个基于 Go 的低资源 OpenClaw 风格助手，面向超小硬件和极低内存预算。",
      card3Meta1: "状态：已确认公开仓库",
      card3Meta2: "适合：边缘设备和低成本硬件",
      card4Tag: "容器优先",
      card4Body: "一个强调容器化执行和更安全隔离的轻量替代方案。",
      card4Meta1: "状态：已确认公开仓库",
      card4Meta2: "适合：安全和容器化部署",
      card5Tag: "Rust",
      card5Body: "一个基于 Rust 的运行时和基础设施路线，并提供面向 OpenClaw 用户的迁移能力。",
      card5Meta1: "状态：已确认公开仓库",
      card5Meta2: "适合：偏基础设施和迁移需求的用户",
      card6Tag: "生态",
      card6Body: "官方技能市场和注册表，用于发现、安装和发布 OpenClaw skills。",
      card6Meta1: "状态：已确认官方项目",
      card6Meta2: "适合：发现和分发技能",
      card7Tag: "工作流",
      card7Body: "官方工作流和编排格式，适合多 agent 的 OpenClaw 使用方式。",
      card7Meta1: "状态：已确认官方生态",
      card7Meta2: "适合：结构化多 agent 工作流",
      ctaEyebrow: "一起扩充目录",
      ctaTitle: "想让你的 OpenClaw 项目被收录？",
      ctaBody: "通过提交页发送项目名称、链接、简短介绍和上线说明。",
      ctaButton: "立即提交",
      footerText: "一个公开的 OpenClaw 项目导航站。",
    },
    about: {
      title: "关于 | OpenClaw Finder",
      description: "了解 OpenClaw Finder 是什么、适合谁，以及项目收录标准。",
      eyebrow: "关于",
      bodyTitle: "为什么做这个站",
      body1:
        "OpenClaw Finder 是一个面向 OpenClaw 生态的精选导航站，目的是让用户更容易发现项目、快速比较，并持续跟踪新的发布内容，而不是在零散链接之间来回搜索。",
      section1Title: "什么项目会被收录",
      section1Body:
        "收录对象应与 OpenClaw 生态直接相关，并且需要提供可访问的官网、代码仓库或产品页面。站点会为了清晰和一致性对条目进行适度编辑。",
      section2Title: "如何审核",
      section2Body: "所有提交内容都会先人工审核，再决定是否展示在站点中，以减少低质量条目。",
    },
    submit: {
      title: "提交项目 | OpenClaw Finder",
      description: "提交 OpenClaw 项目，申请在 OpenClaw Finder 上收录。",
      eyebrow: "提交",
      bodyTitle: "提交你的 OpenClaw 项目",
      body1: "当前阶段采用人工收录。你可以通过邮件发送以下信息，提交后会进入审核。",
      emailLabel: "邮箱：",
      includeLabel: "请包含：",
      includeBody: "项目名称、URL、一句话简介，以及它和其他项目的区别。",
      body2: "等你配置好邮箱转发或表单工具后，可以把这个页面替换成真实表单。",
    },
    contact: {
      title: "联系 | OpenClaw Finder",
      description: "联系 OpenClaw Finder，提交项目、反馈问题或咨询赞助合作。",
      eyebrow: "联系",
      bodyTitle: "联系我",
      body1: "你可以通过邮件反馈目录问题、提交修正、咨询合作，或沟通后续广告与赞助。",
      emailLabel: "邮箱：",
      responseLabel: "回复时间：",
      responseBody: "通常会在几个工作日内回复。",
    },
    privacy: {
      title: "隐私政策 | OpenClaw Finder",
      description: "OpenClaw Finder 的隐私政策说明。",
      eyebrow: "隐私",
      bodyTitle: "隐私政策",
      body1: "OpenClaw Finder 可能会收集基础分析信息，例如页面访问量、来源页面和浏览器信息，用于了解网站使用情况。",
      body2: "如果你通过邮件提交项目或发送联系请求，你的消息和联系方式只会用于审核项目或回复咨询。",
      body3: "未来站点可能会接入第三方分析或广告服务。在启用这些服务之前，应更新本页面内容。",
    },
  },
};

const pageTextKeys = {
  about: { title: "about.title", description: "about.description" },
  submit: { title: "submit.title", description: "submit.description" },
  contact: { title: "contact.title", description: "contact.description" },
  privacy: { title: "privacy.title", description: "privacy.description" },
  home: { title: "home.title", description: "home.description" },
  "project-openclaw": { title: "project.openclaw.title", description: "project.openclaw.description" },
  "project-picoclaw": { title: "project.picoclaw.title", description: "project.picoclaw.description" },
  "project-nanoclaw": { title: "project.nanoclaw.title", description: "project.nanoclaw.description" },
  "project-zeroclaw": { title: "project.zeroclaw.title", description: "project.zeroclaw.description" },
  "project-clawhub": { title: "project.clawhub.title", description: "project.clawhub.description" },
  "project-openprose": { title: "project.openprose.title", description: "project.openprose.description" },
  "project-qclaw": { title: "project.qclaw.title", description: "project.qclaw.description" },
};

function getValue(language, key) {
  return key.split(".").reduce((value, part) => value && value[part], translations[language]);
}

function detectLanguage() {
  const saved = window.localStorage.getItem("preferred-language");
  if (saved === "zh" || saved === "en") return saved;
  const language = (navigator.language || "").toLowerCase();
  return language.startsWith("zh") ? "zh" : "en";
}

function applyLanguage(language) {
  const page = document.body.dataset.page || "home";
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";

  for (const element of document.querySelectorAll("[data-i18n]")) {
    const key = element.dataset.i18n;
    const value = getValue(language, key);
    if (typeof value === "string") element.textContent = value;
  }

  const metaDescription = document.getElementById("meta-description");
  const pageKeys = pageTextKeys[page];
  if (pageKeys) {
    document.title = getValue(language, pageKeys.title);
    if (metaDescription) metaDescription.setAttribute("content", getValue(language, pageKeys.description));
  }

  for (const button of document.querySelectorAll("[data-lang-button]")) {
    const isActive = button.dataset.langButton === language;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  }
}

document.addEventListener("DOMContentLoaded", () => {
  const initialLanguage = detectLanguage();
  applyLanguage(initialLanguage);

  for (const button of document.querySelectorAll("[data-lang-button]")) {
    button.addEventListener("click", () => {
      const language = button.dataset.langButton;
      window.localStorage.setItem("preferred-language", language);
      applyLanguage(language);
    });
  }
});
